# Form implementation generated from reading ui file '/home/rangelgbr/Workspace/Projects/MetricsKitchen/gui/pages/pages.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_AppPages(object):
    def setupUi(self, AppPages):
        AppPages.setObjectName("AppPages")
        AppPages.resize(400, 301)
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pageHome)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.pageHome)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        AppPages.addWidget(self.pageHome)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        AppPages.addWidget(self.page_2)
        self.pageSettings = QtWidgets.QWidget()
        self.pageSettings.setObjectName("pageSettings")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pageSettings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.pageSettings)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        AppPages.addWidget(self.pageSettings)

        self.retranslateUi(AppPages)
        QtCore.QMetaObject.connectSlotsByName(AppPages)

    def retranslateUi(self, AppPages):
        _translate = QtCore.QCoreApplication.translate
        AppPages.setWindowTitle(_translate("AppPages", "StackedWidget"))
        self.label.setText(_translate("AppPages", "Initial Page"))
        self.label_2.setText(_translate("AppPages", "Página 2"))
        self.label_3.setText(_translate("AppPages", "Página 3"))
